spring.application.name=hospital-reservation-system

# MySQL 연결
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/hospital_reservation?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=Dkssudgktpdy1288@

# MyBatis 설정
mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.type-aliases-package=com.hospital.reservation
mybatis.configuration.map-underscore-to-camel-case=true

# 로그 설정
logging.level.com.hospital.reservation=DEBUG